export const REQUEST_SEARCH = 'REQUEST_SEARCH';
export const SEARCH_STARTED = 'SEARCH_STARTED';
export const SEARCH_FINISHED = 'SEARCH_FINISHED';
export const FOUND_RESULT = 'FOUND_RESULT';
export const TOGGLE_SELECTED_TYPE = 'TOGGLE_SELECTED_TYPE';

export const STOP_SEARCHING = 'STOP_SEARCHING';
